spring.application.name=Yellow_GateWay


server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


spring.cloud.gateway.server.webflux.routes.-id=yellow-service
spring.cloud.gateway.server.webflux.routes.-uri=lb://yellow-service
spring.cloud.gateway.server.webflux.routes.predicates-Path=/api/**