spring.application.name=Yellow_GateWay


server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webflux.routes[0].id=Yellow
spring.cloud.gateway.server.webflux.routes[0].uri=lb://Yellow
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/**